# Generated by Django 3.2.7 on 2021-09-13 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('upfront_commission_rate', models.IntegerField()),
                ('trial_commission_rate', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
